name: 07 - 6.1 eBPF Clean Build - mrproper + All Maps

# Recreates the original Run 18018422141
# Full eBPF with make mrproper for clean source tree
# Fixed "Source tree is not clean" error

on:
  workflow_dispatch:

jobs:
  build-clean-ebpf:
    strategy:
      matrix:
        include:
          - version: "6.1"
            sub_level: 112
            os_patch_level: 2024-11
          - version: "6.1"
            sub_level: 115
            os_patch_level: 2024-12
          - version: "6.1"
            sub_level: 119
            os_patch_level: 2025-01

    uses: ./.github/workflows/gki-kernel-ebpf.yml
    secrets: inherit
    with:
      version: android14-${{ matrix.version }}
      version_name: android14-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android14-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}