name: 6.1.1x eBPF Clean Build - mrproper + All Maps + CO-RE

# Run ID 18018422141 - Commit 1c26b99c
# Full eBPF with make mrproper for clean source tree
# Fixed "Source tree is not clean" error with proper cleanup before Bazel build

on:
  workflow_dispatch:

jobs:
  build-clean-ebpf:
    strategy:
      matrix:
        include:
          - version: "6.1"
            sub_level: 112
            os_patch_level: 2024-11
          - version: "6.1"
            sub_level: 115
            os_patch_level: 2024-12
          - version: "6.1"
            sub_level: 118
            os_patch_level: 2025-01
    uses: ./.github/workflows/gki-kernel-ebpf.yml
    secrets: inherit
    with:
      version: android14-${{ matrix.version }}
      version_name: android14-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android14-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}